# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mydesign.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(420, 560)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("\n"
"     QWidget {\n"
"         background-color: #f9fafb;\n"
"         font-family: \'Segoe UI\', \'Tahoma\', sans-serif;\n"
"         font-size: 14px;\n"
"         color: #1f2937;\n"
"     }\n"
"\n"
"     QLabel#titleLabel {\n"
"         font-size: 20pt;\n"
"         font-weight: bold;\n"
"         color: #111827;\n"
"         margin-bottom: 10px;\n"
"     }\n"
"\n"
"     QLineEdit {\n"
"         border: 1px solid #d1d5db;\n"
"         border-radius: 8px;\n"
"         padding: 6px 10px;\n"
"         background-color: white;\n"
"     }\n"
"\n"
"     QComboBox {\n"
"         border: 1px solid #d1d5db;\n"
"         border-radius: 8px;\n"
"         padding: 6px 10px;\n"
"         background-color: white;\n"
"     }\n"
"\n"
"     QPushButton {\n"
"         background-color: #2563eb;\n"
"         color: white;\n"
"         border: none;\n"
"         border-radius: 8px;\n"
"         padding: 8px 16px;\n"
"         font-weight: bold;\n"
"     }\n"
"\n"
"     QPushButton:hover {\n"
"         background-color: #1d4ed8;\n"
"     }\n"
"\n"
"     QPushButton:pressed {\n"
"         background-color: #1e40af;\n"
"     }\n"
"\n"
"     QPushButton#removeFavoriteButton {\n"
"         background-color: #dc2626;\n"
"         color: white;\n"
"         font-weight: 600;\n"
"         border-radius: 8px;\n"
"         padding: 8px 12px;\n"
"         margin-top: 10px;\n"
"     }\n"
"\n"
"     QPushButton#removeFavoriteButton:hover {\n"
"         background-color: #b91c1c;\n"
"     }\n"
"\n"
"     QPushButton#removeFavoriteButton:pressed {\n"
"         background-color: #7f1d1d;\n"
"     }\n"
"\n"
"     QCheckBox {\n"
"         margin-top: 10px;\n"
"     }\n"
"\n"
"     QLabel#translationLabel {\n"
"         font-size: 16px;\n"
"         font-weight: 500;\n"
"         color: #374151;\n"
"         padding: 10px;\n"
"         border: 1px solid #d1d5db;\n"
"         border-radius: 8px;\n"
"         background-color: #ffffff;\n"
"     }\n"
"\n"
"     QLabel#statusLabel {\n"
"         font-size: 12px;\n"
"         color: green;\n"
"         margin-top: 8px;\n"
"     }\n"
"\n"
"     QLabel#favoritesLabel {\n"
"         font-size: 18pt;\n"
"         font-weight: 600;\n"
"         margin-top: 20px;\n"
"         color: #111827;\n"
"     }\n"
"\n"
"     QTableView {\n"
"         border: 1px solid #d1d5db;\n"
"         border-radius: 8px;\n"
"         background-color: white;\n"
"     }\n"
"    ")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.titleLabel = QtWidgets.QLabel(self.centralwidget)
        self.titleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.verticalLayout.addWidget(self.titleLabel)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.languageComboBox = QtWidgets.QComboBox(self.centralwidget)
        self.languageComboBox.setObjectName("languageComboBox")
        self.languageComboBox.addItem("")
        self.languageComboBox.addItem("")
        self.languageComboBox.addItem("")
        self.languageComboBox.addItem("")
        self.languageComboBox.addItem("")
        self.languageComboBox.addItem("")
        self.languageComboBox.addItem("")
        self.languageComboBox.addItem("")
        self.languageComboBox.addItem("")
        self.verticalLayout.addWidget(self.languageComboBox)
        self.rememberCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.rememberCheckBox.setObjectName("rememberCheckBox")
        self.verticalLayout.addWidget(self.rememberCheckBox)
        self.translateButton = QtWidgets.QPushButton(self.centralwidget)
        self.translateButton.setObjectName("translateButton")
        self.verticalLayout.addWidget(self.translateButton)
        self.translationLabel = QtWidgets.QLabel(self.centralwidget)
        self.translationLabel.setText("")
        self.translationLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.translationLabel.setObjectName("translationLabel")
        self.verticalLayout.addWidget(self.translationLabel)
        self.statusLabel = QtWidgets.QLabel(self.centralwidget)
        self.statusLabel.setText("")
        self.statusLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.statusLabel.setObjectName("statusLabel")
        self.verticalLayout.addWidget(self.statusLabel)
        self.favoritesLabel = QtWidgets.QLabel(self.centralwidget)
        self.favoritesLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.favoritesLabel.setObjectName("favoritesLabel")
        self.verticalLayout.addWidget(self.favoritesLabel)
        self.favoritesTableView = QtWidgets.QTableView(self.centralwidget)
        self.favoritesTableView.setMinimumHeight(120)
        self.favoritesTableView.setObjectName("favoritesTableView")
        self.verticalLayout.addWidget(self.favoritesTableView)
        self.removeFavoriteButton = QtWidgets.QPushButton(self.centralwidget)
        self.removeFavoriteButton.setObjectName("removeFavoriteButton")
        self.verticalLayout.addWidget(self.removeFavoriteButton)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "სიტყვების თარგმნა"))
        self.titleLabel.setText(_translate("MainWindow", "სიტყვების თარგმნა"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "ჩაწერეთ სიტყვა"))
        self.languageComboBox.setItemText(0, _translate("MainWindow", "English to Spanish"))
        self.languageComboBox.setItemText(1, _translate("MainWindow", "English to French"))
        self.languageComboBox.setItemText(2, _translate("MainWindow", "English to German"))
        self.languageComboBox.setItemText(3, _translate("MainWindow", "English to Italian"))
        self.languageComboBox.setItemText(4, _translate("MainWindow", "English to Japanese"))
        self.languageComboBox.setItemText(5, _translate("MainWindow", "English to Georgian"))
        self.languageComboBox.setItemText(6, _translate("MainWindow", "Georgian to English"))
        self.languageComboBox.setItemText(7, _translate("MainWindow", "French to English"))
        self.languageComboBox.setItemText(8, _translate("MainWindow", "German to English"))
        self.rememberCheckBox.setText(_translate("MainWindow", "ფავორიტებში დამახსოვრება"))
        self.translateButton.setText(_translate("MainWindow", "თარგმნა"))
        self.favoritesLabel.setText(_translate("MainWindow", "ფავორიტები"))
        self.removeFavoriteButton.setText(_translate("MainWindow", "მონიშნულის ამოშლა"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
